// src/components/Testimonials.tsx
import { Card } from '@/components/ui/card';

interface Testimonial {
  name: string;
  company: string;
  quote: string;
}

const testimonials: Testimonial[] = [
  {
    name: 'Ricardo Silva',
    company: 'Silva Imóveis',
    quote:
      'A DS Desenvolvimento transformou completamente nossa presença digital. Em menos de 3 meses, o volume de leads triplicou.',
  },
  {
    name: 'Ana Oliveira',
    company: 'BioEstética',
    quote: 'Site extremamente rápido e design premium que transmite autoridade imediata.',
  },
  {
    name: 'Marcos Vinícius',
    company: 'TechSolutions',
    quote: 'Código limpo, performance absurda e resultado no Google impecável.',
  },
  {
    name: 'Juliana Costa',
    company: 'Fashion Store',
    quote: 'SEO Local colocou nossa empresa no topo do Google Maps.',
  },
  {
    name: 'Carlos Eduardo',
    company: 'Clínica Sorriso',
    quote:
      'Excelente trabalho no SEO Local. Hoje somos a primeira opção quando alguém busca por dentista na região.',
  },
  {
    name: 'Marina Lima',
    company: 'Arquitetura & Design',
    quote:
      'O design do site ficou incrível. Conseguiu transmitir exatamente a sofisticação que meus projetos exigem.',
  },
  {
    name: 'Paulo André',
    company: 'Suplementos Prime',
    quote:
      'A integração com o WhatsApp facilitou demais nosso atendimento. Leads qualificados chegando todos os dias.',
  },
  {
    name: 'Roberta Santos',
    company: 'Advocacia Integrada',
    quote:
      'Profissionalismo e entrega no prazo. O site é leve, rápido e passa muita confiança para os nossos clientes.',
  },
  {
    name: 'Felipe Neves',
    company: 'Construtora Neves',
    quote:
      'Nossa landing page de lançamentos imobiliários superou todas as expectativas de conversão e captação de leads.',
  },
  {
    name: 'Beatriz Rocha',
    company: 'Buffet Gourmet',
    quote:
      'O novo site nos trouxe clientes de grandes eventos corporativos que antes não conseguíamos alcançar.',
  },
];

export default function Testimonials() {
  return (
    <div className="relative py-16 overflow-hidden group">
      {/* Blur edges estilo Stripe/Neon */}
      <div className="pointer-events-none absolute left-0 top-0 h-full w-32 bg-gradient-to-r from-background to-transparent z-10" />
      <div className="pointer-events-none absolute right-0 top-0 h-full w-32 bg-gradient-to-l from-background to-transparent z-10" />

      {/* Container da animação */}
      <div className="flex w-fit animate-marquee gap-6 px-6 group-hover:[animation-play-state:paused]">
        {/* Duplicamos a lista para criar o efeito infinito sem saltos */}
        {[...testimonials, ...testimonials].map((t, i) => (
          <div key={i} className="flex-shrink-0">
            <Card className="w-[350px] p-6 rounded-2xl glass border-white/10 hover:border-brand-primary/50 transition-colors duration-500 h-full flex flex-col justify-between">
              <p className="text-sm text-muted-foreground leading-relaxed italic">“{t.quote}”</p>

              <div className="mt-6 border-t border-white/5 pt-4">
                <div className="font-semibold text-foreground">{t.name}</div>
                <div className="text-xs text-brand-primary/80 font-medium">{t.company}</div>
              </div>
            </Card>
          </div>
        ))}
      </div>
    </div>
  );
}

// src/components/Testimonials.vue
<template>
  <div class="testimonials-container relative py-10">
    <div class="absolute inset-y-0 left-0 w-20 bg-gradient-to-r from-white dark:from-[#020617] to-transparent z-10 pointer-events-none"></div>
    <div class="absolute inset-y-0 right-0 w-20 bg-gradient-to-l from-white dark:from-[#020617] to-transparent z-10 pointer-events-none"></div>

    <swiper-container
      :slides-per-view="1.2"
      :space-between="20"
      :loop="true"
      :speed="5000"
      :autoplay="{
        delay: 0,
        disableOnInteraction: false,
      }"
      :free-mode="true"
      :breakpoints="{
        640: { slidesPerView: 2 },
        1024: { slidesPerView: 3.5 },
        1440: { slidesPerView: 4.5 }
      }"
      class="continuous-swiper"
    >
      <swiper-slide v-for="(item, index) in testimonials" :key="index" class="h-auto">
        <!-- Adicionado h-full e min-h-[320px] para padronização -->
        <div class="glass-card p-8 rounded-3xl h-full min-h-[320px] flex flex-col justify-between hover:translate-y-[-8px] transition-all duration-500 group border border-white/20 dark:border-white/10">
          <div>
            <div class="text-vue-green mb-2 text-4xl opacity-50 font-serif">"</div>
            <p class="text-gray-600 dark:text-gray-300 italic mb-6 leading-relaxed text-sm md:text-base">
              {{ item.quote }}
            </p>
          </div>
          
          <div class="flex items-center gap-4 border-t border-gray-100 dark:border-white/5 pt-6">
            <img :src="item.image" :alt="item.name" class="w-12 h-12 rounded-full border-2 border-vue-green object-cover flex-shrink-0" />
            <div class="min-w-0">
              <h4 class="font-bold text-vue-blue dark:text-white text-sm truncate">{{ item.name }}</h4>
              <p class="text-[10px] text-gray-500 font-medium tracking-tight uppercase truncate">{{ item.company }}</p>
            </div>
          </div>
        </div>
      </swiper-slide>
    </swiper-container>
  </div>
</template>

<script setup>
import { register } from 'swiper/element/bundle';
register();

const testimonials = [
  {
    name: "Ricardo Silva",
    company: "Silva Imóveis",
    quote: "A DS Desenvolvimento transformou completamente nossa presença digital. Em menos de 3 meses, o volume de leads qualificados triplicou.",
    image: "https://i.pravatar.cc/150?u=ricardo"
  },
  {
    name: "Ana Oliveira",
    company: "BioEstética",
    quote: "O site é extremamente rápido e o design Liquid Glass passa uma autoridade incrível para nossos clientes de alto padrão.",
    image: "https://i.pravatar.cc/150?u=ana"
  },
  {
    name: "Marcos Vinícius",
    company: "TechSolutions",
    quote: "Trabalho com tecnologia e sou exigente. O código deles é limpo e a performance no Google é impecável. Recomendo!",
    image: "https://i.pravatar.cc/150?u=marcos"
  },
  {
    name: "Juliana Costa",
    company: "Fashion Store",
    quote: "O Google Maps agora é nossa maior fonte de clientes locais. A estratégia de SEO Local da equipe foi o divisor de águas.",
    image: "https://i.pravatar.cc/150?u=juliana"
  },
  {
    name: "Fabio Mendes",
    company: "Mendes Advocacia",
    quote: "Nossa Landing Page converte 4x mais que o site antigo. A clareza da proposta de valor e a velocidade fazem toda a diferença.",
    image: "https://i.pravatar.cc/150?u=fabio"
  },
  {
    name: "Carla Souza",
    company: "FitLife Academia",
    quote: "A gestão de anúncios trouxe um ROI que nunca tínhamos visto antes. O suporte da equipe DS é excepcional e proativo.",
    image: "https://i.pravatar.cc/150?u=carla"
  },
  {
    name: "Bruno Guedes",
    company: "Guedes Logística",
    quote: "Eles entendem de negócio, não só de código. A consultoria estratégica inicial poupou meses de erros no nosso marketing.",
    image: "https://i.pravatar.cc/150?u=bruno"
  }
];
</script>

<style scoped>
.continuous-swiper::part(wrapper) {
  transition-timing-function: linear !important;
}

swiper-slide {
  height: auto;
}

.glass-card {
  background: rgba(255, 255, 255, 0.4);
  backdrop-filter: blur(12px);
  -webkit-backdrop-filter: blur(12px);
  box-shadow: 0 8px 32px 0 rgba(31, 38, 135, 0.07);
}

:global(.dark) .glass-card {
  background: rgba(255, 255, 255, 0.05);
  box-shadow: 0 8px 32px 0 rgba(0, 0, 0, 0.3);
}
</style>
